#!/bin/bash

confirm() {
params=( "$1" "$2" "$3" "$4" "$5" "$6")
rval=5
while ((rval > 3));do
    echo -ne "${params[0]} ${params[1]}"
    ans=
    rval=
    IFS= read -r -n1 ans
    if [ -z "$ans" ] || ((${#ans} > 1)); then
        ((rval=4))
    else
        case "$ans" in
            [${params[2]}]*)
                rval=0
                ;;
            [${params[3]}]*)
                rval=1
                ;;
            [${params[4]}]*)
                rval=2
                ;;
            [${params[5]}]*)
                rval=3
                ;;
            *)
                rval=4
                ;;
        esac
    fi
done
echo $rval
return $rval
}

fastupdt() {
cd freedv-rade/freedv-gui
. ./rade-venv/bin/activate
cd build_linux
if ! [[ -h model19_check3 ]]; then
    ln -s $(pwd)/rade_src/model19_check3 model19_check3
fi
PYTHONPATH="$(pwd)/rade_src:$PYTHONPATH" make
cd
}

# Check we are not root
((UID)) || { echo "You must NOT be root user to run $0, use CTRL/d to become $USER"; exit 1; }

# Check we have internet and DNS
ping -c3 google.com > /dev/null || { echo "Failed to find internet connection or DNS"; exit 1; }

# Do all from user's home folder
cd

# Check that freedv-rade-build is there
[[ -d freedv-rade-build ]] || { echo -e "The freedv-rade-build folder is missing!\nFollow the instructions in the README #at:\nhttps://github.com/barjac/freedv-rade-build\n"; exit 1; }

# Preamble
clear
echo "################## Welcome to freedv-rade-update ######################"
echo -e "\n This script is for maintaining a build of FreeDV RADE development version\n \
created using freedv-rade-build script.\n"
echo -e "It will optionally:\n \
* Update FreeDV to the latest git master. (fast, recommended) \n \
* Fully rebuild FreeDV from scratch. \n \
* Create a backup of the current version in use.\n \
* Restore from a previous backup.\n\n\
Nothing will be done until you finally confirm after the summary."

# Check if there is already a backup and flag it
[[ -d freedv-rade_bak ]] && bak=1

if (( bak == 1 )); then
    confirm "\nDo you want to (U)pdate, (F)ull re-build, (B)ackup or (R)estore from an existing backup?" "[U/F/B/R]" "Uu" "Ff" "Bb" "Rr"
    val=$?
    if (( val == 0 )); then
        fastupdt=1
    elif (( val == 1 )); then
        update=1
    elif (( val == 2 )); then
        backup=1
    elif (( val == 3 )); then 
        restore=1
    fi
else
    confirm "\nDo you want to (U)pdate, (F)ull re-build  or (B)ackup?" "[U/F/B]" "Uu" "Ff" "Bb"
    val=$?
    if (( val == 0 )); then
        fastupdt=1
    elif (( val == 1 )); then
        update=1
    elif (( val == 2 )); then
        backup=1
    fi
fi
#echo "U=$fastupdt F=$update B=$backup R=$restore" 
if ( (( fastupdt == 1 )) || (( update == 1 )) || (( backup = 1 )) ) && (( bak != 1 )) && (( restore != 1 )); then
# Ask to backup with the current version
    echo -e "\nYou currently have no backup of FreeDV."
    if confirm "\nCreate a backup of the current version?" "[Y/N]" "Yy" "Nn";then
         backup=1
        # Check we have space
        (( $(df -hBG --output=avail /home |tr '\n' ' '|tr -s ' '|cut -d ' ' -f2|cut -dG -f1) > 3 )) || { echo -e "\nInsufficient disk space for backup"; backup=0; }
    fi
fi
if (( bak == 1 )) && (( restore != 1 )); then
    echo -e "\nYou already have a backup of a previous FreeDV build."
    if confirm "Replace the current backup with a new one of the current version?" "[Y/N]" "Yy" "Nn";then
        backup=1; overwrite=1
    else
        backup=0
    fi
fi

# Summary of what will be done
if (( fastupdt == 1 )) || (( update == 1 )) || (( backup == 1 )) || (( restore == 1 )); then
    echo -e "\nSummary of selected tasks:\n"
    if (( backup == 1 )) ; then
        if (( bak == 1 )); then 
            if (( overwrite == 1 )); then
                echo "A new backup will be created overwriting the old backup."
            else
                echo "A new backup will be created."
            fi
        else
            echo "A backup will be created."
        fi
    elif (( restore != 1 )); then 
        echo "No backup will be created."
    fi

    if (( fastupdt == 1 )); then
        echo "FreeDV will be updated to the latest version (github commit)."
    fi

    if (( update == 1 )); then 
        echo "FreeDV will be fully re-built from the current github branch master."
    fi

    if (( restore == 1 )); then
        echo -e "FreeDV will be restored from your current backup which will remain in place.\nThis will overwrite your current version."
    fi

    if confirm "\nPerform the selected tasks?" "[Y/N]" "Yy" "Nn";then

# Fast update
        if (( fastupdt == 1 )); then
            echo -e "\nStarting fast update in 5 seconds..."
            sleep 5
            fastupdt
            (( $? == 0 )) && echo "Update Complete"
        fi

# Create backup
        if (( backup == 1)); then
            echo -e "\nCreating backup..."
            rm -rf freedv-rade_bak/
            cp -rf freedv-rade/ freedv-rade_bak
            (( $? == 0 )) && echo "Backup complete."
        fi

# Restore from backup
        if (( restore == 1)); then
            echo -e "\nRestoring from backup..."
            rm -rf freedv-rade/
            cp -rf freedv-rade_bak/ freedv-rade
            (( $? == 0 )) && echo "Restore complete."
        fi

# Full re-build
        if (( update == 1 )); then 
            echo -e "\nStarting full rebuild in 5 seconds. Please be patient this will take some time ..."
            sleep 5
            freedv-rade-build/freedv-rade-build
        fi
    else
        echo -e "\nAborting then - bye! :("
        exit 0
    fi
else
    echo -e "\nNothing to do - bye! :)"
    exit 0
fi
