#!/bin/bash
# This script adds a FreeDV-RADE .desktop file to the desktop.

# Check we are not root
((UID)) || { echo "You must NOT run $0 as root - aborting!"; exit 0; }

# Create .desktop file only if missing (don't overwrite existing)
if ! [[ -f $(xdg-user-dir DESKTOP)/freedv-rade.desktop ]]; then
cat > $(xdg-user-dir DESKTOP)/freedv-rade.desktop <<EOF
[Desktop Entry]
Version=1.0
Name=FreeDV-RADE
Exec=/home/$USER/freedv-start
Icon=/home/$USER/freedv-rade-build/freedv.png
Type=Application
Terminal=true
Categories=AudioVideo;Audio;HamRadio;
Comment=Digital Voice mode for HF Radio
Keywords=Radio;HAM;HF;RF;codec2;voice;modem;
X-Desktop-File-Install-Version=0.26

EOF

    if [[ -f $(xdg-user-dir DESKTOP)/freedv-rade.desktop ]]; then
        chmod +x $(xdg-user-dir DESKTOP)/freedv-rade.desktop || echo "WARNING: failed to chmod desktop file"
        echo "FreeDV-RADE Desktop file created"
	fi
fi
