#!/bin/bash
# This script adds a FreeDV-RADE .desktop file to the desktop.

# Check we are not root
((UID)) || { echo "You must NOT run $0 as root - aborting!"; exit 0; }

cd
# Create .desktop file only if missing (don't overwrite existing)
if ! [[ -f ~/Desktop/freedv-rade-update.desktop ]]; then
cat > ~/Desktop/freedv-rade.desktop <<EOF
[Desktop Entry]
Version=1.0
Name=FreeDV-RADE-Update
Exec=~/freedv-rade-build/freedv-rade-update
Icon=~/freedv-rade-build/freedv.png
Type=Application
Terminal=true
Categories=AudioVideo;Audio;HamRadio;
Comment=Digital Voice mode for HF Radio
Keywords=Radio;HAM;HF;RF;codec2;voice;modem;
X-Desktop-File-Install-Version=0.26

EOF

chmod +x Desktop/freedv-rade-update.desktop
fi
